### PR TITLE
added podspec

### PR DESCRIPTION
**Pull request by fabb**
added podspec from CocoaPods/Specs repo and updated version number to 0.6

### CODE REVIEW

**Comment by fabb** [comment]
I just copied the existing podspec from here and changed the version number: https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/e/2/6/libextobjc/0.4.1/libextobjc.podspec.json

**Comment by diederich** [comment]
Oh, one thing: I guess we need to make this a 0.6.1 to make it work, assuming cocoa pods tries to find the Podspec in the given version? 

Once we merge this PR, we can then tag 0.6.1 version which holds the pod spec.

**Comment by fabb** [comment]
No this is not neccessary. There are a few ways to pecify pods in a Podfile, for our case the relevant ones are these two:

1. the default way: specify a pod without url, just with a version
```
pod 'libextobjc/EXTKeyPathCoding', '0.6.1'
```
This makes it necessary that the podspec is pushed to the CocoaPods/Specs repository. In this case it is **not** necessary that the podspec is committed to the repo. This is possible for libextobjc versions up until 0.4 since someone donated a podspec to the Specs repo. 


```
pod 'libextobjc/EXTKeyPathCoding', :git => 'https://github.com/jspahrsummers/libextobjc.git', :commit => '02305659fb9cc464fffda5f2d977e21cbac6a07e'
```

**Comment by diederich** [comment]
Nice, thanks for the clarifications @fabb - that makes sense.

**Pull request merged**
